### ISSUE TITLE
Unresponsive performance issue

### ISSUE THREAD

**Issue by Jounin022** [iulian-radu-at/find-unused-exports#1]
that extension actually doesn't work in some large projects , im trying to search unused exports but all i got is an infinite loading and a description Unresponsive performance issue on vscode .

**Comment by iulianraduat** [comment]
Hi Johnny,

As I cannot have access to your project to see where is the bottleneck,  it will be great if you can provide me some metrics of your project so I can try to reproduce it. Some metrics can be: number of files, min/max number of exports and imports per file, type of exports and imports.

I will try to add a setting to the plugin so an user can produce a log of what the plugin is doing. Maybe this will improve the debug experience 🤔

Cheers,
Iulian

**Comment by iulianraduat** [comment]
I will close this issue with the hope that more information will be provided in the future.

**Comment by iulianraduat** [comment]
@Johnny-Brendow Can you please install at least the version 1.1.0 and mark in settings that you want to produce a log?
Then you can see in which file is the extension "blocking" and we can check what it is different with that file. Thanks
