### ISSUE TITLE
The extension won't finish loading

### ISSUE THREAD

**Issue by luigiraven** [iulian-radu-at/find-unused-exports#10]
**Describe the bug**
After installing it seems like the extension started working on finding the unused exports, but after over 30min it is still loading and it wont show anything on screen

**Expected behavior**
I would expect the extension to give some feedback about how long it will take it to finish, or to prompt any kind of error if anything that would stop the procedure has happened

**To Reproduce**
1. Install the extension
2. The extension would show a loading state and it wouldn't show anything else 

**Information about the extension:**
 - Version: 1.8.0
 - Enabled features
   - [ x ] find unused exports
   - [  ] find circular dependecies

**Information about your project:**
 - Type of files:
   - [  ] .js / .jsx
   - [ x ] .ts / .tsx
 - [ x ] It has a tsconfig.json file 
 - Number of files
   - [  ] .js / .jsx
   - [ 658 ] .ts / .tsx

**Screenshots**
![image](https://user-images.githubusercontent.com/85901778/129918665-279e2f0a-8a7b-4295-8c91-62b86a49c86b.png)

**Additional context**
N/A

**Comment by iulianraduat** [comment]
Hi @luigiraven,

I just released a new version (1.9.0). The matching expressions for finding the imports and exports were complex and sometimes they got hung. The new versions uses a different approach, so getting feedback from you if it works it is important.

Many thanks for your help,
Iulian

**Comment by iulianraduat** [comment]
Closed as there was no input provided from issuer.
