### ISSUE TITLE
support .svelte files

### ISSUE THREAD

**Issue by opensas** [iulian-radu-at/find-unused-exports#12]
**Describe the bug**
When working with svelte framework .svelte files are ignored

**Expected behavior**
detect when exported typescript members are used from .svelte files

**Comment by iulianraduat** [comment]
Hi @opensas,

You can scan them by adding the glob for your .svelte files in tsconfig.json or jsconfig.json.

```json
{
   "include": [
     ...,
    "src/**/*.svelte"
  ],
}
```

**Comment by iulianraduat** [comment]
Hi @opensas,

In v1.12.0 was added support to define additinal include(s) in package.json or .findUnusedExports.json
Please take a look, try to use it and let me know if it works for you.

Thanks,
Iulian

**Comment by iulianraduat** [comment]
Hi @opensas,

In v1.14.0 it was added the display of the number of matches for an include rule.
Can you please confirm that this version fixes your problem? Namely that the expected number of svelte files were found.

Thanks,
Iulian

**Comment by opensas** [comment]
Thanks a lot for your prompt reply, sorry I couldn't anser before.

I created this test repo: https://github.com/opensas/find-unused-export-sveltekit

I created this helper lib at [`src/lib/utils.ts`](https://github.com/opensas/find-unused-export-sveltekit/blob/main/src/lib/utils.ts) ([link](https://github.com/opensas/find-unused-export-sveltekit/blob/main/src/lib/utils.ts))

![image](https://user-images.githubusercontent.com/481687/154702361-e8c59081-03b7-4918-977f-62a3541a7305.png)

And I'm using only `usedFromMarkup` and `usedFromScript` functions from [`src/routes/index.Svelte`](https://github.com/opensas/find-unused-export-sveltekit/blob/main/src/routes/index.svelte) ([link](https://github.com/opensas/find-unused-export-sveltekit/blob/main/src/routes/index.svelte)

![image](https://user-images.githubusercontent.com/481687/154702511-2d1a0cbd-fbcd-4c1c-88e7-5f6a312c9f7f.png)

This is what the extensions reports:

![image](https://user-images.githubusercontent.com/481687/154702592-5b7a5fa7-b7b0-484e-8408-2bf27832fdf1.png)

It doesn't detect the functions being used from the `.svelte` file

and this is my [`tsconfig.json`](https://github.com/opensas/find-unused-export-sveltekit/blob/main/tsconfig.json) file: (sveltekit default tsconfig file, [link](https://github.com/opensas/find-unused-export-sveltekit/blob/main/tsconfig.json))

```
{
	[...]
	"include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"]
}
```

using version 1.14.1

![image](https://user-images.githubusercontent.com/481687/154702706-c7f5f856-9a99-4a92-b447-4da439bfcf38.png)

---

also tried adding svelte files to my [package.json](https://github.com/opensas/find-unused-export-sveltekit/blob/main/package.json#L31) and also adding a [.findUnusedExports.json](https://github.com/opensas/find-unused-export-sveltekit/blob/main/.findUnusedExports.json) with the same result

**Comment by iulianraduat** [comment]
Great @opensas,

I will check it and let you know what I found.

Cheers,
Iulian

**Comment by iulianraduat** [comment]
Hi @opensas,

I found the "problem". It is the way you import the file in svelte (the dollar sign before lib):
```
import { usedFromMarkup, usedFromScript } from '$lib/utils';
```

If you change the import to the following one, your app will work as before and the used exported consts are correctly found:
```
import { usedFromMarkup, usedFromScript } from '../lib/utils';
```

I know that this can mean a lot of refactoring but this extension is though to recognize only imports used in .js or .ts files.

Please test what I found and let me know if this resolves your problem.

Cheers,
Iulian

**Comment by opensas** [comment]
Yes, it works!

we are so close to get it perfect.

that is a default path mapping that comes with every sveltekit app.

it is defined [here](https://github.com/opensas/find-unused-export-sveltekit/blob/2b6ba9b2ca49109ed3d195af1fbff7fb3d3aea93/tsconfig.json#L30):

```json
		"paths": {
			"$lib": ["src/lib"],
			"$lib/*": ["src/lib/*"]
		}
```

If you could somehow take these into account (I think it's a regular `tsconfig.json` file) that would be great.

Or at least to somehow enter an equivalent configuration for `find-unused`exports`.

**Comment by iulianraduat** [comment]
Hi @opensas,

I will close this and open a new issue for a feature request to implement support for [paths in tsconfig.json](https://www.typescriptlang.org/tsconfig#paths) .

**Comment by opensas** [comment]
> Hi @opensas,
> 
> I will close this and open a new issue for a feature request to implement support for [paths in tsconfig.json](https://www.typescriptlang.org/tsconfig#paths) .

yes, that sounds great, I'll sure keep and eye on that  issue
