### ISSUE TITLE
Stuck in endless loop (reproduction inside 😄 )

### ISSUE THREAD

**Issue by HarmHoeksema** [iulian-radu-at/find-unused-exports#13]
**Describe the bug**
The extension is stuck in an **endless loop** if you do the following:

my tsconfig.json looked like this:
`"include": ["src/client/**/*", "src/server/**/*", "src/shared/**/*",],`

Only **after** creating .findUnusedExports.json I could finally see the debug window. 
Error parsing "c:\<>\tsconfig.json": "Unexpected token ] in JSON at position 97"

So yeah, there was an additional comma in my tsconfig. Still I think the extension shouldn't be stuck in an endless loop basically making the whole vscode stuck. Try the tsconfig.json edit and see what happens in vscode 😄

**Comment by iulianraduat** [comment]
Hi @FloodGames,

JSON.parse is pretty sensible. What you think, in the case JSON.parse cannot parse package.json should be displayed the error also in a information message?

Thanks,
Iulian

**Comment by HarmHoeksema** [comment]
Display the parse error in the GUI under 'Overview' (plus the debug window), and return out of running/cancel the rest of the application? 

Clearly people should fix their json settings first _(which is also helpful)_ . I think this also fixes an earlier '[complaint](https://github.com/iulian-radu-at/find-unused-exports/issues/10)' about not running. If people know why, it is ten times better experience, versus not knowing why.

**Comment by iulianraduat** [comment]
Besides package.json the user can define now include and exclude files using the .findUnusedExports.json file. So I think that we should not stop the process if package.json is not "well formatted". Maybe there are users which needs a "broken" package.json, like comments or extra commas.

**Comment by HarmHoeksema** [comment]
Try it. Put the comma there and break vscode by clicking on your extension 😄

**Comment by iulianraduat** [comment]
That is what I am doing now. Having fun with breaking my own extension 😂

**Comment by HarmHoeksema** [comment]
> That is what I am doing now. Having fun with breaking my own extension 😂

I wonder: Is it searching the whole known universe for unused exports?

Here: https://youtu.be/EumXak7TyQ0?t=530

**Comment by iulianraduat** [comment]
I still cannot reproduce the **endless loop** 😞

**Comment by HarmHoeksema** [comment]
> I still cannot reproduce the **endless loop** 😞

oh? 
1. remove the .findUnusedExports.json file 
2. edit tsconfig.json `"include": ["src/client/**/*", "src/server/**/*", "src/shared/**/*",], `with the extra comma
3. restart vscode
4. click your extension on the sidebar
5. Endless loop -> vscode broken

**Comment by HarmHoeksema** [comment]
Hmmm.. when using another TS project i can't replicate it as well.... 

any chance to get a debug to you when it is running too long?

_" [debug] findImportsBlock > No `import` tokens found"_ maybe?

**Comment by iulianraduat** [comment]
@FloodGames maybe can you find what makes different the project which produced the loop?

**Comment by HarmHoeksema** [comment]
We discussed, apparently it was including an output folder with a lot of .js files (during developing .ts it creates new .js every time)
