### ISSUE TITLE
Bug: package.json main files not counting

### ISSUE THREAD

**Issue by JoelDohmKaratjas** [iulian-radu-at/find-unused-exports#15]
**Describe the bug**
If you import a folder containing a package.json with a main file in it, the extension shows whatever is in the main file as an unused export.

**Expected behavior**
The main file exports to be counted as a used imports.

**Information about the extension:**
 - Version: 1.15.2

**Information about your project:**
 - Type of files:
   - [x] .js / .jsx
   - [x] .ts / .tsx

**Screenshots**
![Code_hiJm6EyMdG](https://user-images.githubusercontent.com/33188727/157799249-0a0150f5-28b5-4c93-913c-4d734fa8787f.png)
![Code_776ExYoIpR](https://user-images.githubusercontent.com/33188727/157799456-3ca88935-c838-4fe6-9dda-1d34b790ad56.png)

**Comment by iulianraduat** [comment]
Hi @BlakeIsMyWaifu ,

Thanks for your feedback. I have doubts if we should consider all exports in a main file as being used.

For the moment, you can use the following code to mark these exports as being used:
```
// find-unused-exports:ignore-next-line-exports
```

I will let this issue open in the hope that more people will comment on this.

Cheers,
Iulian

**Comment by iulianraduat** [comment]
I added a setting in 1.18.0 which allows to force all exports from the main file to be considered used.
