### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ger9000** [iulian-radu-at/find-unused-exports#16]
- Issue Type: `Performance`
- Extension Name: `find-unused-exports`
- Extension Version: `1.15.3`
- OS Version: `Darwin x64 21.4.0`
- VS Code version: `1.66.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/yc/kk_4vxhn1837lr068fjst98ssk_98l/T/iulian-radu-at.find-unused-exports-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by iulianraduat** [comment]
Hi @ger9000,

Sorry for the delayed answer.

The process of scanning the folders for matching files and read their content can be cpu intensive. Nothing that can be improved here. Sorry.
