### ISSUE TITLE
Working with workspaces

### ISSUE THREAD

**Issue by francescovdd** [iulian-radu-at/find-unused-exports#17]
**Describe the bug**
If I use a workspace with a simple node api & nextjs frontend I'm not able to find any file, if I open the frontend as single folder it works

**Expected behavior**
Should find files

**Comment by iulianraduat** [comment]
Hi @francescovdd ,

Can you please enable the debug and send it to me?

Also some steps on how I can reproduce your repo (so I can test the extension on it) will be very appreciated.

Thanks,
Iulian

**Comment by iulianraduat** [comment]
Closed as there was no feedback from reporter.
