### ISSUE TITLE
Progress indicator during initial scan

### ISSUE THREAD

**Issue by ash211** [iulian-radu-at/find-unused-exports#18]
I tried running this extension on a large repo and it took a long time to run (250s for the first scan).  During this time I considered uninstalling the extension because I didn't know if it would ever succeed on this repo.

Please provide some sort of progress indicator during the scan so that users can roughly tell if the extension will finish ~soon or ~never.

Thanks!

**Comment by iulianraduat** [comment]
It is provided in 1.17.0 as an indicator in status bar.
