### ISSUE TITLE
False positive on `.js` imports

### ISSUE THREAD

**Issue by gamesaucer** [iulian-radu-at/find-unused-exports#20]
**Describe the bug**
The plugin does not recognise imports with a `.js` extension as a use of that export from the corresponding `.ts` file. This is valid TypeScript that compiles to working JavaScript, and moreover, is understood by IntelliSense and packages such as dpdm. The TSC does not add `.js` extensions to imports when compiling, so using `.js` is correct and necessary for this purpose.

**Expected behavior**
If a file `Foo.ts` imports `Bar` from `Baz.js`, the `Bar` export in `Baz.ts` should not be marked as unused.

**To Reproduce**
1. Create a new TS project
2. Add the following code:

    ```ts
    // Baz.ts
    export const Bar = 'Bar'
  
    // main.ts
    import { Bar } from 'Baz.js'
    ```
3. The extension now incorrectly marks `Bar` as unused.

**Information about the extension:**
 - Version: 1.16.0
 - Enabled features
   - [x] find unused exports
   - [ ] find circular dependecies

**Information about your project:**
 - Type of files:
   - [x] .js / .jsx
   - [x] .ts / .tsx
 - [x] It has a tsconfig.json file

**Comment by iulianraduat** [comment]
Hi @gamesaucer,

As I see this kind of import (import from a generated .js instead from the .ts) as more of a hack I will wait for the community feedback if this extension should support it.

Being "understood by IntelliSense" does not automatically means that it is also correct. IntelliSense tries to collect as much suggestions as possible and not to validate the meanings.

Thinks also to the following use case:
* there is a .js and a .ts files, both having the same filename (except the extension) but with different content
* they can both exists in a project/repo as are two different files
* which imports should have precedence (if any)?

Cheers,
Iulian

**Comment by iulianraduat** [comment]
Closed as there was no response from the community.
