### ISSUE TITLE
No files checked if package.json is not in the root folder

### ISSUE THREAD

**Issue by JosuaKrause** [iulian-radu-at/find-unused-exports#21]
**Describe the bug**
If package.json is not in the root folder of the project there is no way to tell the extension where to look for files.
Even placing `.findUnusedExports.json` in the root folder does not work.

**Expected behavior**
Placing a `.findUnusedExports.json` in the root folder of the project should be enough to specify where files can be found. Even if no package.json is in that folder.

**Comment by iulianraduat** [comment]
Hi @JosuaKrause ,

I try to understand your use case. Why do you want to check for unused exports in a project without package.json?
Is it missing also jsconfig.json and tsconfig.json?

A work around is to create a minimal package.json.

Cheers,
Iulian

**Comment by iulianraduat** [comment]
Closed as there was no response from the reporter.
