### ISSUE TITLE
Saving 'index.tsx': Running 'TypeScript and JavaScript Language Features' Formatter (configure)

### ISSUE THREAD

**Issue by igregor** [iulian-radu-at/find-unused-exports#23]
Type: <b>Bug</b>

When I try to save any ts file it says:

Saving 'index.tsx': Running 'TypeScript and JavaScript Language Features' Formatter (configure)

I used this issue for debugging
https://github.com/microsoft/vscode/issues/133427

Extension version: 1.20.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 5.14.0-1057-oem
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 3, 2|
|Memory (System)|31.09GB (25.46GB free)|
|Process Argv|. --crash-reporter-id 3f6305b0-417f-4b5a-8e9d-ba6f3bef876b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30662443

```

</details>

**Comment by iulianraduat** [comment]
Hi @igregor,

Some questions:
* what you mean by 'I used this issue for debugging'?
* is it your problem related to this extension?
  * if yes, why do you think so/how do you know that?
  * if you disable this extension, is the problem gone?
  * is the problem triggered when you display for the first type the extension's panel or later?
* how can be reproduced this problem?

Simply saving an index.tsx file should not trigger anything in this extension as it does not formatting (the refresh is done at the start and then only on request).

Thanks,
Iulian

**Comment by igregor** [comment]
Hey @iulian-radu-at 

I have the extension enabled globally, however, I have not been using it recently.

Let me answer your questions:
- I'm referring to this comment: https://github.com/microsoft/vscode/issues/133427#issuecomment-922783588 `Start Extension Bisect`
- yes:
  - VS code tells me that when I use `Start Extension Bisect`
  - yes
  - I could not save any file at all, the `index.tsx` was only an example

However, I tried to enable the extension today back again and there is no issue with saving and formatting. 
I'm closing the issue for now as not reproducible.
