### ISSUE TITLE
Extension is showing a lot of false positives

### ISSUE THREAD

**Issue by cheesyMan** [iulian-radu-at/find-unused-exports#26]
**Describe the bug**
After the last update, the extension is showing a lot of false positives.

Example: 
```
// App.tsx
export default App;

// main.tsx
import App from './App';
```

Extension shows warning >> **src/App.tsx default not used**.

**Expected behavior**
Correct unused exports warnings.

**Information about the extension:**
 - Version: [1.21.0]
 - Enabled features
   - [  ] find unused exports
   - [  ] find circular dependecies

![Snipaste_2023-05-04_10-34-45](https://user-images.githubusercontent.com/55018265/236152817-62368394-dd07-49d5-bcd8-267518bbde45.jpg)

**Information about your project:**
 - Type of files:
   - [  ] .js / .jsx
   - [ X ] .ts / .tsx
 - [ X ] It has a tsconfig.json file 
 - Number of files
   - [ 0 ] .js / .jsx
   - [ 102 ] .ts / .tsx

**Comment by iulianraduat** [comment]
Hi @cheesyMan,

Many thanks for reporting this problem.

Please try the version 1.21.1 and let me know if it works as expected.

Cheers,
Iulian

**Comment by cheesyMan** [comment]
> Hi @cheesyMan,
> 
> Many thanks for reporting this problem.
> 
> Please try the version 1.21.1 and let me know if it works as expected.
> 
> Cheers, Iulian

Hi @iulian-radu-at, I can confirm that the issue is gone in version 1.21.1
Thanks!
