### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by skynolimits247** [iulian-radu-at/find-unused-exports#27]
- Issue Type: `Performance`
- Extension Name: `find-unused-exports`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.70.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/AKASHS~1/AppData/Local/Temp/iulian-radu-at.find-unused-exports-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by iulianraduat** [comment]
Hi @skynolimits247,

In v2.0.0 was fixed the amount of files being scanned by the extension. Maybe can you try the latest version and see if your problem still persist? Thank you.

Can you provide some information about your project?
* Type of project - js/ts
* Number of files
* Is the problem triggered in a folder or workspace?
* Has the workspace multiple roots?
* What type of imports are you using? - static, dynamic, lazy
* Do you have a lot of comments in your code? - the extension tries to remove them as inside can be imports/exports which needs to be ignored
* Can you check if there is something wrote in the Output window of the extension and send me its content?

Thanks your helping to improve this extension.
Iulian

**Comment by prmichaelsen** [comment]
A silly fix, but you can disable the extension until you need it for cleanup

**Comment by iulianraduat** [comment]
Or you can create a vscode profile which has my extension installed and use that profile only when you want to check the project

**Comment by iulianraduat** [comment]
Closed as there was not any activity since some time
