### ISSUE TITLE
False positive when using import as types

### ISSUE THREAD

**Issue by jahvi** [iulian-radu-at/find-unused-exports#28]
**Describe the bug**
The extension reports files as having circular imports when imported as `type`.

**Expected behavior**
Files imported as `type` shouldn't be reported as having circular imports.

**To Reproduce**

**Hello.ts**

```ts
import type { World } from './World';

class Hello {
    public world: World;
}
```

**World**
```ts
import type { Hello } from './Hello';

class World {
    something(hello: Hello) {
        //...
    }
}
```

**Information about the extension:**
 - Version: 2.1.1
 - Enabled features
   - [x] find unused exports
   - [x] find circular dependecies

**Information about your project:**
 - Type of files:
   - [x] .js / .jsx
   - [  ] .ts / .tsx
 - [x] It has a tsconfig.json file 
 - Number of files
   - [  ] .js / .jsx
   - [x] .ts / .tsx: 2,000+

**Screenshots**
N/A

**Additional context**
Maybe I'm misunderstanding but having type imports shouldn't be reported as these are removed by TS in the compilation step anyways so they should be fine.

**Comment by iulianraduat** [comment]
Hi @jahvi,

Thanks for your message.

You are right that these imports are not present in javascript.
But I also think that having the kind of code you presented above is not good practice (A using B using A using ...). So I would like this plugin to report this to me. As I am subjective, I would like to ask the community what they think.

Cheers,
Iulian

**Comment by sharky98** [comment]
Hello,

On my side, it is not in the circular import, but for TS types and interfaces that are defined in their own files. They are always shown as unused even if they are used through `import type { something } from './my-types.ts'`. Maybe adding a configuration to consider `import type` as used?

**Comment by iulianraduat** [comment]
Hi @sharky98,

I tried to reproduce your problem but I could not.
Maybe can you provide a small example so I can reproduce it? Preferable in a different issue than this one.

Thanks,
Iulian

**Comment by iulianraduat** [comment]
Closed as there was not answer from reporter.
