### ISSUE TITLE
Unable to load on larger project

### ISSUE THREAD

**Issue by benhamiltonpro** [iulian-radu-at/find-unused-exports#3]
I have a larger project and it just spins with no output in the `Extension` terminal with debugging enabled. The only error I get is in the Log (Window) terminal stating:
`
[2021-02-15 10:39:04.243] [renderer1] [warning] UNRESPONSIVE extension host, 'iulian-radu-at.find-unused-exports' took 98% of 5078.875ms, saved PROFILE here: 'c:\Users\benha\AppData\Local\Temp\exthost-c3c265.cpuprofile' [{"id":"iulian-radu-at.find-unused-exports","total":5001143,"percentage":98},{"id":"program","total":77602,"percentage":2}]
`

I have also attached the referenced cpuprofile.
[exthost-c3c265.zip](https://github.com/iulian-radu-at/find-unused-exports/files/5982615/exthost-c3c265.zip)

**Comment by iulianraduat** [comment]
Hi @benhamiltonpro,

Did you activated the debug for this extension? It could help to figure out in which step it blocks.
It tries to create a list with all matching .ts and .js files. Maybe this is the problem 🤔
Maybe there are some circular dependencies for project's folders?

Cheers,
Iulian

**Comment by benhamiltonpro** [comment]
Hello,

I do have the debug enabled for the extension and it is not logging anything to the output console.
We are using .js files.
There are some dependency cycles in the project. Is there any way around that for this extension?

Thanks,
Ben

**Comment by iulianraduat** [comment]
Hi @benhamiltonpro,

I created a circular dependency between my folders and I do not have any problem using the latest version of this extension. If you are using a older version, can you please trying with the latest one?

The dependency cycles of imports is controllable with findUnusedExports.detectCircularImports in VSCode's settings and it is false by default.

Waiting to hear news from you,
Iulian

**Comment by iulianraduat** [comment]
Closed as being inactive
