### ISSUE TITLE
Issue when types in a module are exported within an export { } statement rather than one by one

### ISSUE THREAD

**Issue by cheesyMan** [iulian-radu-at/find-unused-exports#31]
**Describe the bug**
I usually **group** my exports in a single `export {}` statement at the end of the module, so I have a clear and quick view of what I am exporting, without having to check all along the module.

So, typically my modules look like this:

```
// my-module.ts

type A = {
  //
}

type B = {
  //
}

function C() {
  //
}

export {
  A,
  B,
  C
}
```

However, because of the `"isolatedModules":true` configuration in **tsconfig.json** (that is required by **Vite**: https://vitejs.dev/guide/features#typescript-compiler-options), this way of exporting will generate this error from Typescript: _Re-exporting a type when 'isolatedModules' is enabled requires using 'export type' .ts(1205)_.

So, I need to change my global export to:

```
export {
  type A,
  type B,
  C
}
```
Now, Typescript stops complaining, but `find-unused-exports` will detect always my types exports as unused (image attached), even if they are imported in other modules:

![Snipaste_2024-03-16_09-26-58](https://github.com/iulian-radu-at/find-unused-exports/assets/55018265/74cf7e5b-51e2-4f6f-8628-cee0a4b4b6f8)

If I export my types one by one, no error occurs:

```
export type A {
  // 
}
```

Another option would be to set `"isolatedModules":false` in tsconfig.json, but this would deactivate many other useful error detections from Typescript + Vite and - anyway - I'm not allowed to do that :).

**Expected behavior**
A correct detection of unused exports even when the types are exported in a single export {} statement

**To Reproduce**
1. set `"isolatedModules":true` in tsconfig.json
2. export types in a single statement in this shape:
```
export {
  type A,
  type B
  //...
}
```
3. import types in other modules
4. check `find-unused-exports` output

**Information about the extension:**
 - Version: 2.1.1
 - Enabled features
   - [X] find unused exports
   - [ ] find circular dependecies

**Information about your project:**
 - Type of files:
   - [ ] .js / .jsx
   - [X] .ts / .tsx
 - [X] It has a tsconfig.json file

**Comment by iulianraduat** [comment]
Hi @cheesyMan,

Thanks for reporting it. I will investigate it.

Cheers,
Iulian

**Comment by cheesyMan** [comment]
Hi @iulian-radu-at,

If I can add some extra info, there is also another possible scenario.
<br>

If I export **ONLY TYPES** from a module (so, no functions or other variables), the export statement could be as well like this:
```
// my-module.ts
// the 'type' keyword is put outside the curly braces,
// as I'm exporting only types
export type {
  A,
  B
}
```
In this case I get:  
- no errors raised by Typescript
- `find-unused-exports` does not reports any unused export, even if the types are actually NOT imported anywhere
<br>

**Original Scenario** (the one described in my original post): 
```
// my-module.ts
// the 'type' keyword is repeated for each export
export {
  type A,
  type B
}
```
In this case I get:
- no errors raised by Typescript
- `find-unused-exports` reports unused export for every item (with that _weird joining_ of the 'type' keyword with the exported name, like 'typeA', 'typeB'), even they are actually imported somewhere

**Comment by iulianraduat** [comment]
Hi @cheesyMan,

Please test your project with at leat version 2.1.2 and let me know if it works.

Cheers,
Iulian

**Comment by cheesyMan** [comment]
Hi @iulianraduat,
it seems working perfectly now, thanks. 👍
