### ISSUE TITLE
The used function marked as unused.

### ISSUE THREAD

**Issue by Guck111** [iulian-radu-at/find-unused-exports#4]
**Describe the bug**
The used function marked as unused.
In my case, the Archetype function is imported into two files.

**Information about the extension:**
 - Version: [e.g. 1.4.3]
 - Enabled features
   - find unused exports

 - Type of files:
   -  .ts / .tsx

**Screenshots**
<img width="1146" alt="Screenshot 2021-04-23 at 16 09 06" src="https://user-images.githubusercontent.com/19519268/115876892-870bc800-a44f-11eb-8e0d-72dc65bb2d2c.png">
<img width="1150" alt="Screenshot 2021-04-23 at 16 09 31" src="https://user-images.githubusercontent.com/19519268/115876903-8a06b880-a44f-11eb-9e4b-5131cf59150b.png">

**Comment by iulianraduat** [comment]
Hi @Guck111,

Sorry for the late response. I just so now your message.

From your screenshot of references I see an export and an re-export of Archetype.

Also in Router.tsx is a res.Archetype, and unfortunately there is no view of the code from Router.tsx so I can understand why you have it like that. I assume that res is the result of a require()? If so, then this extension is not taking into consideration this kind of imports.

Please share also the code in Router.tsx related to res and res.Archetype as I want to better understand your use case.

Thanks,
Iulian

**Comment by iulianraduat** [comment]
Hi @Guck111,

Can you please install at least version 1.8.0 and see if the exports are correctly detected as used or not?

Cheers,
Iulian

**Comment by iulianraduat** [comment]
Closed as no response from reporter.
