### ISSUE TITLE
Not finding files

### ISSUE THREAD

**Issue by HarmHoeksema** [iulian-radu-at/find-unused-exports#5]
**Describe the bug**
```
Path to project: "c:\\GIT\\<project>"
Processed files: 0
Files having imports|exports: 0
Total imports: 0
Total exports: 0
Analysed files: 0
Not used exports: 0
Found circular imports: 0
Ellapsed time (ms): 3
```

**Expected behavior**
My code is in 
./src/server/
./src/client/
./src/shared/

What's used to find the code?
Does it exclude node_modules automatically? (I hope)

Note that I have 2 entry files. index.js and a serverDev.js

**Comment by HarmHoeksema** [comment]
Update:
removing this line from my tsconfig.json and it started working
`"include": ["src/client/**/*", "src/server/**/*", "src/shared/**/*"]`

Does it mean your extension cannot handle this input?
Or should I change my include?

**Comment by iulianraduat** [comment]
Hi @FloodGames,

Many thanks for posting this issue. Based on it I found out and corrected the algorithm for finding the source files.

Please install at least the version 1.5.0 and let me know if it works for your project without changing your tsconfig.json (by removing the include).

Cheers,
Iulian

**Comment by HarmHoeksema** [comment]
**Yes it works :D.** 

I wonder that sometimes the right side is 'empty' sometimes not showing a description, instead of like "not used"
![image](https://user-images.githubusercontent.com/60991890/119203464-6311c580-ba93-11eb-9e53-ea77729eeda3.png)

I hope the algorithm can be approved, because I also think it sees a lot of functions that actually used. 
Like: 
export specific -> export again via an index.js -> used

**Comment by HarmHoeksema** [comment]
Can you show it to the right-side of the function instead of hover perhaps?
![image](https://user-images.githubusercontent.com/60991890/119203742-18447d80-ba94-11eb-88b2-a2f2b66670f8.png)

Also wonder if there is a circular dependency.
