### ISSUE TITLE
Bug: Improving Unused algorithm due to multi-level exports

### ISSUE THREAD

**Issue by HarmHoeksema** [iulian-radu-at/find-unused-exports#6]
**Describe the bug**
Basically this use-case gives false-positives on unused exports.

export specific -> export again via an index.js -> used

![image](https://user-images.githubusercontent.com/60991890/119203908-783b2400-ba94-11eb-98f2-5c6c5b213747.png)

I can also imagine that this is not a best practice, I'm not sure

**Comment by iulianraduat** [comment]
Hi @FloodGames,

I improved the code so it can handle a larger number of use cases.
Please install at least 1.7.1 and see if it works for you.
Also please let me know if it is faster (some numbers will also be great).

Cheers,
Iulian

**Comment by HarmHoeksema** [comment]
unfortunately it seems to get stuck in an endless loop and I can't get Output debug to work to give you more info.

**Comment by iulianraduat** [comment]
Hi @FloodGames,

Thanks for heads up. Maybe you can tell me more about your project?
Is it a typescript, javascript or mixed project?
Are there symlinked/hardlinked files?
Is only one project, or many in one folder?
Is the detectCircularImports enabled? (if yes please turn it off and see if it helps)

I will add a setting so the log to be saved also in a file. Unfortunatelly VSCode does not allow me to flush the output so we have this case where nothing is displayed :(

Cheers,
Iulian

**Comment by iulianraduat** [comment]
As this is the same with https://github.com/iulian-radu-at/find-unused-exports/issues/9 I will close it.
