### ISSUE TITLE
Suggestion: Seperate Circular dependency, Unused Exports and Overview in GUI with tab

### ISSUE THREAD

**Issue by HarmHoeksema** [iulian-radu-at/find-unused-exports#7]
**Describe the bug**
In madge, Circular dependency are written like this:

a.ts -> b.ts -> c.ts -> a.ts

**Expected behavior**
I think a seperate tab should be shown in the GUI to express this, including 'Overview'. Perhaps with the hierarchy as the circular files?

**Unused Functions**
d.ts   
. -> function A _not used_
. -> function B _not used_
**Circular Dependencies**
a.js  _circular dependency_
.  -> b.js
.     ...  -> c.js

If nothing is found: _"None found, searched in 55 files"_ 
This gives decent detail if it actually worked 👍 
Also circular should be on by default I think, if that works.

### GUI 
**Unused Functions**
_"None found, searched in 55 files"_

**Circular Dependencies**
a.js  _circular dependency_

**Overview**
Processed files: 432
Files having imports|exports: 292
Total imports: 2082
Total exports: 791

**Comment by iulianraduat** [comment]
Hi @FloodGames,

This looks like a good idea, but I would like to see more users "voting" for it.

**Comment by iulianraduat** [comment]
Hi @FloodGames,

Your feature request was implemented in v1.12.0
Please install it and let me know what you think, eventually suggest improvements 😄 

Cheers,
Iulian

**Comment by HarmHoeksema** [comment]
It seems great! Also like that you can refresh easily to test. 

I just really suck at solving the circular dependencies.  Imagine different rooms and RoomManager... seems impossible to fix.

Anyhow! I think your extension will be 1**0.000+ downloads at the end of this year!** _(now at 28)_

**Comment by iulianraduat** [comment]
Resolving circular imports is quite easy 😛 

When are circular imports happening
1. the easiest case: A - B - A
2. the other case: A - B - C - A, ...
(A, B, C are files; dash means that the file on left side is importing from the file in the right side):

Solution for case 1:
* merge the two files in a new one
  * the resulting file can be too big 
* extract in a new file the common part
  * the common part can be a type, variable or function
  
Solution for case 2:
* we need to try to reduce the length of the chain (ex: A - B - C - A), using the solutions provided for the previous case
  * during this process it is OK if you produce more chains, but of shorter length (ex: A - B - A, B - C - B) 

If you need help I can try to help you 😃

**Comment by iulianraduat** [comment]
Closing this Issue as the feature request was implemented in v1.12
