### ISSUE TITLE
Suggestion: unused methods

### ISSUE THREAD

**Issue by HarmHoeksema** [iulian-radu-at/find-unused-exports#8]
When you have an object Dog, with method bark
And that method is never called anywhere. I would like to know. 

**Unused Methods:**
b.js 
-> bark  unused method

**Comment by iulianraduat** [comment]
HI @FloodGames,

Finding unused methods is something more for eslint than for this extension.

Maybe https://github.com/sindresorhus/eslint-plugin-unicorn can help you?

Cheers,
Iulian

**Comment by iulianraduat** [comment]
Closed as it will not be implemented
